apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
#postgres Base64 String: superman@google.com
#echo -n postgres | base64

  DB_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==

  # EstoEsUnPassWirdSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzV2lyZFNlY3JldG8=