apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
#postgres Base64 = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=

  # EstoEsUnPassWordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzV2lyZFNlY3JldG8=